name: CI

on:
    pull_request:
        branches: ["main"]

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Code Checkout
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm ci

            - name: TypeScript Compile
              run: npm run compile

    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Code Checkout
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm ci

            - name: ES Lint
              run: npm run lint
